image: maven:3-jdk-11

stages:
    - build
    - test
    - sonar

build :
    stage: build
    script:
        - ./mvnw clean install
        - ./mvnw compiler:compile
        - echo "Built successfuly"

test:
    stage: test
    script: 
        - ./mvnw test
        - echo "successful"

sonar:
    stage: sonar
    script: 
        - ./mvnw sonar:sonar -Dsonar.projectKey=swagon-api
        - ./mvnw sonar:-Dsonar.host.url=http://localhost:9000
        - ./mvnw sonar:-Dsonar.login=b291d76d4afa705b38b6744956bb04b9538bf13d